---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/",
  out.width="100%"
)
```

# PIFDataModel

## Overview

The **PIFDataModel** R package is part of the [PIF Database Project](https://pif.esa.ipb.pt/), which aims to facilitate the sharing and usage of the structured data and JSON schemas associated with the Pathogens in Foods (PIF) Database. This package serves as a repository for database structures, schemas, and related resources to support researchers, food safety professionals, and decision-makers in analyzing data related to pathogens in food.

## Features

- Access to PIF database structures.
- Tools to validate and manipulate PIF database schemas (under development).

## Installation

To install the development version of **PIFDataModel**, use the following commands in R:

```R
# Install the remotes package if you don't have it
install.packages("remotes")

# Install the PIFDataModel package
remotes::install_github("fsqanalytics/PIFDataModel")
```

## Acknowledgments

The PIF Database and this package are developed as part of a research project funded by the European Food Safety Authority (EFSA). Special thanks to all contributors and collaborators who support this initiative.

---

Visit the [PIF Database Website](https://pif.esa.ipb.pt/) for more information on the broader project.